//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcsGroupAcsArea
    {
        public int ID { get; set; }
        public Nullable<int> AcsGroupID { get; set; }
        public Nullable<int> AcsAreaID { get; set; }
    
        public virtual AccessArea AccessArea { get; set; }
        public virtual AccessGroup AccessGroup { get; set; }
    }
}
