//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaySchedule
    {
        public int ID { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> AccessTypeID { get; set; }
        public Nullable<int> DayTypeID { get; set; }
    
        public virtual AccessType AccessType { get; set; }
        public virtual DayType DayType { get; set; }
    }
}
