//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceEmp
    {
        public int ID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Finger { get; set; }
        public Nullable<bool> Db { get; set; }
        public Nullable<bool> Picture { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
