//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.DeviceEmps = new HashSet<DeviceEmp>();
            this.DeviceSchGroups = new HashSet<DeviceSchGroup>();
            this.Settings = new HashSet<Setting>();
        }
    
        public int ID { get; set; }
        public string DeviceName { get; set; }
        public string IP { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<int> SettingID { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<int> UDPPort { get; set; }
        public string DeviceSerial { get; set; }
        public string RegistrationCode { get; set; }
        public string ActivationCode { get; set; }
        public string ServerIP { get; set; }
        public string webUser { get; set; }
        public string webPass { get; set; }
        public Nullable<int> TypeId { get; set; }
    
        public virtual DeviceType DeviceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceEmp> DeviceEmps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceSchGroup> DeviceSchGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setting> Settings { get; set; }
    }
}
