//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee:ICloneable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Cards = new HashSet<Card>();
            this.DeviceEmps = new HashSet<DeviceEmp>();
            this.Faces = new HashSet<Face>();
            this.Fingers = new HashSet<Finger>();
        }

        private Employee employee;

        public int ID { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<int> AcsGroupID { get; set; }
        public string EmpFname { get; set; }
        public string EmpLname { get; set; }
        public string EmpNationalCode { get; set; }
        public string PersonalNum { get; set; }
        public string EmpPinCode { get; set; }
        public string AuthenticationMode { get; set; }
        public string TelePhone { get; set; }
        public string Post { get; set; }
        public Nullable<bool> HasFinger { get; set; }
        public byte[] Image { get; set; }
        public Nullable<bool> HasCard { get; set; }
        public string MenuAccess { get; set; }
        public Nullable<bool> IsGuest { get; set; }
        public Nullable<bool> PrivateAccess { get; set; }
        public Nullable<bool> SendToZK { get; set; }
        public Nullable<bool> IsAdmin { get; set; }

          
    
        public virtual AccessGroup AccessGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Cards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceEmp> DeviceEmps { get; set; }
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Face> Faces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Finger> Fingers { get; set; }

        public object Clone()
        {
            return this.MemberwiseClone();
        }
    }
}
