//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finger
    {
        public int ID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> FingerNum { get; set; }
        public byte[] Data { get; set; }
        public string Md5 { get; set; }
        public Nullable<int> DataLength { get; set; }
        public string EnrollTime { get; set; }
        public Nullable<int> fingerQuality { get; set; }
        public string PdpID { get; set; }
        public string DataStr { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
