//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int ID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public string EchoDir { get; set; }
        public string EchoName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> DHCP { get; set; }
        public string IP { get; set; }
        public string Subnet { get; set; }
        public string gateway { get; set; }
        public Nullable<bool> ServerEnabled { get; set; }
        public string ServerIP { get; set; }
        public string ServerPort { get; set; }
        public string UDPPort { get; set; }
        public Nullable<int> TimeOutMenu { get; set; }
        public Nullable<int> NormalBrightness { get; set; }
        public Nullable<int> SleepBrightness { get; set; }
        public Nullable<bool> LockHomeScreen { get; set; }
        public Nullable<bool> VacationDuty { get; set; }
        public Nullable<bool> DeviceInfo { get; set; }
        public string AuthenticationType { get; set; }
        public Nullable<bool> Relay { get; set; }
        public string RelayDuration { get; set; }
        public Nullable<int> RelayDriven { get; set; }
        public Nullable<bool> Audio { get; set; }
        public Nullable<bool> PreventConsecutive { get; set; }
        public Nullable<int> ConsecutivePassessDelay { get; set; }
        public string WebUser { get; set; }
        public string WebPass { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
